ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<n>',views.addtocart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove<n>',views.cart_remove,name="cart_remove"),
    path('full_remove<n>',views.full_remove,name="full_remove"),
    path('orderform',views.orderform,name="orderform"),
    path('ordervew',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
# from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [

    path('',views.search,name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.allcategories,name="allcat"),
    path('products/<p>',views.allproducts,name="allprod"),
    path('details/<p>',views.details,name="details"),
    path('register',views.register,name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price


class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    ordered_date=models.DateTimeField(auto_now_add=True)
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")

    def __str__(self):
        return self.product.name

class Account(models.Model):
    acctnum=models.IntegerField()
    acctype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to="images/category",null=True,blank=True)

    def __str__(self):
        return self.name
class Product(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to="images/product",null=True,blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)  #foreign key
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import Product
from cart.models import Cart,Account,Order
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def cartview(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    total=0
    for i in cart:
        total+=i.quantity*i.product.price
    return render(request,'cartview.html',{'c':cart,'total':total})
@login_required
def addtocart(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock > 0):
            cart.quantity+=1
            cart.save()
            p.stock-=1
            p.save()
    except:
        if (p.stock > 0):
            cart=Cart.objects.create(product=p,user=u,quantity=1)
            cart.save()
            p.stock-=1
            p.save()
    return cartview(request)
@login_required
def cart_remove(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
            p.stock +=1
            p.save()
        else:
            cart.delete()
            p.stock += 1
            p.save()
    except:
        pass
    return cartview(request)
@login_required
def full_remove(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        cart.delete()
        p.stock +=cart.quantity
        p.save()
    except:
        pass
    return cartview(request)
@login_required
def orderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']

        u=request.user
        cart=Cart.objects.filter(user=u)

        total=0
        for i in cart:
            total=i.quantity*i.product.price
        try:
            num=int(n)
            ac=Account.objects.get(acctnum=num)
            if(ac.amount >= total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg="Your order placed successfully"
                return render(request, 'orderdetail.html', {'msg': msg})
                # return HttpResponse("Ordered")
            else:
                msg="Insufficient Amount.You can't Place Order"
                return render(request, 'orderdetail.html', {'msg': msg})
                # return HttpResponse("Insufficient")
        except:
            pass


    return render(request,'orderform.html')
@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from django.db.models import Q
from shop.models import Product
# Create your views here.
def search(request):
    query = ""
    p = None
    if(request.method=="POST"):
        query=request.POST['q']
        p=Product.objects.filter(Q(name__icontains=query)|Q(desc__icontains=query))
    return render(request,'search.html',{'query':query,'p':p})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category
from shop.models import Product
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
# Create your views here.
def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=Product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})

def details(request,p):
    pd=Product.objects.get(name=p)
    return render(request,'detail.html',{'pd':pd})

def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        fname=request.POST['f']
        lname=request.POST['l']
        e=request.POST['e']
        if(p==cp):
            u=User.objects.create_user(username=u,password=p,first_name=fname,last_name=lname,email=e)
            u.save()
            return redirect('shop:login')
        else:
            return HttpResponse("Passwords are not same")
    return render(request,'register.html')

def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
        else:
            return HttpResponse("Invalid credentials")
    return render(request,'login.html')

@login_required()
def user_logout(request):
    logout(request)
    # return HttpResponse("Logout")
    return redirect('shop:login')

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!--google fonts link--->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Slabo+27px&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--static style.css link--->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <div class="container-fluid mt-2">
        <center>
            <img src="{% static 'images/logo1.jpg' %}" height="100px" width="100px">
        </center>
             </div>
            <!-- navbar --->
            <nav class="navbar navbar-expand-lg navbar-light bg-light mt-2 fw-bold">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MY SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">HOME</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ALL CATEGORIES
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allprod' i.name %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>

         {% if user.is_authenticated %}

          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:logout' %}">LOGOUT</a>
        </li>
            {% if user.is_superuser == False %}
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:cartview'%}"><i class="fa-solid fa-cart-shopping"></i><sub>{{count}}</sub></a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
          {% endif %}
          {% else %}
           <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:register' %}">REGISTER</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:login' %}">LOGIN</a>
        </li>
          {% endif %}
      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    </header>

    {% block content %}
    {% endblock %}
<footer class="footer">
    <div class="container-fluid">
        <p class="text-center fw-bold"><i class="fa fa-copyright" aria-hidden="true"></i>Myshop pvt.ltd.All rights Reserved</p>
    </div>
</footer>

</body>
</html>

ecommerce/templates/cartview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <div class="row">
        <h4 class="text-center fw-bold">Shopping Cart</h4>
        <div class="col-7 border border-1">
            <table class="table table-bordered text-center fs-5 mt-2">
                <tr>
                    <th colspan="5">Cart Items</th>
                </tr>
                {% for i in c %}
                <tr>
                    <td>
                        <img src="{{i.product.image.url}}" height="150px" width="150px">
                    </td>
                    <td>
                        <b>{{i.product.name}}</b>
                    </td>
                    <td>
                        <b>ProductID:{{i.product.id}}</b><br>
                        <b>Unit Price:{{i.product.price}}</b><br>
                        <b>Quantity:{{i.quantity}}*{{i.product.price}}</b>
                    </td>
                    <td>
                       <b>Subtotal:{{i.subtotal}} </b>
                    </td>
                    <td>
                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-danger fs-4"></i></a>
                        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger fs-4"></i></a>
                        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-danger fs-4"></i></a>

                    {% else %}

                       <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger fs-4"></i></a>
                        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-danger fs-4"></i></a>
                    {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-4 ms-3">
            <table class="table table-bordered">
                <tr>
                    <th colspan="5">Check Out</th>
                </tr>
                <tr>
                    <th>Total Amount:<span style="position:absolute;right:220px;">{{total}}</span></th>
                </tr>
            </table>
            <center>
            <a href="{% url 'cart:orderform' %}" class="btn btn-danger">Place Order</a>
            <a href="{% url 'shop:allcat' %}" class="btn btn-danger">Continue Shopping</a>
                </center>
        </div>

    </div>
</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid px-2">
        <img src="{% static 'images/banner1.avif' %}" height="522px" width="100%">
    </div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">
        Our Collections
    </h3>
    <p style="text-align:justify;line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</p>
</div>
<div class="container-fluid" style="margin-bottom:100px;">
    <center>
    <div class="row">
        {% for i in c %}
        <div class="col-sm-4">
            <div class="card" style="width:100%;">
              <img src="{{i.image.url}}" class="card-img-top" alt="..." height="300px" width="100%">
              <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <a href="{% url 'shop:allprod' i.name %}" class="btn btn-primary">Products</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
        </center>
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="container-fluid mt-5">
        <div class="row">
            <div class="col-sm-4" style="margin-left:100px;">
                <img src="{{pd.image.url}}" height="400px;" width="100%">
            </div>
            <div class="col-sm-6">
                <h3 class="fw-bold">{{pd.name}}</h3><br>
                <p style="text-align:justify;line-height:2;">{{pd.desc}}</p><br>
                <h5>{{pd.price}}</h5>
                {{pd.stock}}
                {% if user.is_superuser == True %}
                    {% if pd.stock == 0 %}
                        <h3>Out Of Stock</h3>
                    <a href="{% url 'admin:index' %}" class="btn btn-warning">Add Stock</a>
                    {% else %}
                    <h3>Product in Stock</h3>
                    <a href="{% url 'admin:index' %}" class="btn btn-warning">Add Stock</a>
                    {% endif %}

                {% else %}
                    {% if pd.stock == 0 %}
                        <h3>Out Of Stock</h3>
                    {% else %}
                        <a href="{% url 'cart:addtocart' pd.name %}" class="btn btn-warning">Add To Cart</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
  <h1 class="mt-3 mx-3">Login</h1>
<form method="POST" >
   {% csrf_token %}
  <div class="mb-3 ms-3 mt-5" style="width:50%;">
  <label class="form-label fw-bold">Username</label>
  <input type="text" class="form-control " name="u" placeholder="Enter Username">
</div>
<div class="mb-3 ms-3" style="width:50%;">
  <label  class="form-label fw-bold">Password</label>
  <input type="password" class="form-control " name="p" placeholder="Enter Password">
</div>
<div class="mb-3 ms-3" style="width:50%;">
  <input type="submit" class="form-control btn btn-primary" >
</div>
</form>
</center>

{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
<h3 class="text-center mt-2 text-white fw-bold">{{msg}}!!!</h3>
    <h4 class="text-center text-danger">Thank You....</h4>
    <h4 class="text-center"><a href="{% url 'shop:allcat' %}">Continue Shopping</a></h4>
    </div>
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">

    <center>
         <h4 class="fw-bold mt-2">Order Form</h4>
    <form method="POST">
  {% csrf_token %}
 <div class="mb-3 ms-3 mt-3" style="width:50%;">
  <label class="form-label fw-bold">Address</label>
  <input type="text" class="form-control " name="a" placeholder="Enter Address">
</div>
<div class="mb-3 ms-3" style="width:50%;">
  <label  class="form-label fw-bold">Phone</label>
  <input type="number" class="form-control " name="p" placeholder="Enter Phone Number">
</div>
    <div class="mb-3 ms-3" style="width:50%;">
  <label  class="form-label fw-bold">Account Number</label>
  <input type="number" class="form-control " name="n" placeholder="Enter Account Number">
</div>

<div class="mb-5 ms-3" style="width:50%;">
    <button type="submit" class="form-control btn btn-warning fw-bold">Submit</button>
</div>

  </form>
        </center>
</div>
{% endblock %}

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row mt-2 border border-1" style="margin-bottom:100px;">


    {% for i in o %}
    <div class="col-sm-4 ms-5">
        <img src="{{i.product.image.url}}" height="200px" width="200px">

    </div>
    <div class="col-sm-6 me-5 text-center">
        <h3 class=" fw-bold">Name of the Customer:{{u}}</h3>
        <b>ProductName:{{i.product}}</b><br>
        <b>Prodct Price:{{i.product.price}}</b><br>
        <b>Delivery Address:{{i.address}}</b><br>
        <b>Customer Phone:{{i.phone}}</b><br>
        <b>Ordered on:{{i.ordered_date}}</b><br>
        <b>Delivery Status:{{i.delivery_status}}</b><br>
    </div>
        </div>
</div>
    {% endfor %}
{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <img src="{{c.image.url}}" width="100%" height="522px">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">
        {{c.name}}
    </h3>
    <p style="text-align:justify;line-height:2;">
        {{c.desc}}
    </p>
    <div class="container-fluid" style="margin-bottom:100px;">
    <center>
    <div class="row">
        {% for i in p %}
        <div class="col-sm-4">
            <div class="card" style="width:100%;">
              <img src="{{i.image.url}}" class="card-img-top" alt="..." height="300px" width="100%">
              <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                  <p>{{i.price}}</p><br>
                <a href="{% url 'shop:details' i.name %}" class="btn btn-primary">Details</a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
        </center>
</div>
</div>
{% endblock %}

ecommerce/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<center>
    <div class="container" style="border-bottom:100px;">
  <h1 class="mt-3 mx-3 fw-bold">Register</h1>
<form method="POST">
  {% csrf_token %}
 <div class="mb-3 ms-3 mt-3" style="width:50%;">
  <label class="form-label fw-bold">Username</label>
  <input type="text" class="form-control " name="u" placeholder="Enter Username">
</div>
<div class="mb-3 ms-3" style="width:50%;">
  <label  class="form-label fw-bold">Password</label>
  <input type="password" class="form-control " name="p" placeholder="Enter Password">
</div>
    <div class="mb-3 ms-3" style="width:50%;">
  <label  class="form-label fw-bold">Confirm Password</label>
  <input type="password" class="form-control " name="cp" placeholder="Enter Confirm Password">
</div>
    <div class="mb-3 ms-3" style="width:50%;">
  <label  class="form-label fw-bold">First Name</label>
  <input type="text" class="form-control " name="f" placeholder="Enter First Name">
</div>
     <div class="mb-3 ms-3" style="width:50%;">
  <label  class="form-label fw-bold">Last Name</label>
  <input type="text" class="form-control " name="l" placeholder="Enter Last Name">
</div>
     <div class="mb-3 ms-3" style="width:50%;">
  <label  class="form-label fw-bold">Email Address</label>
  <input type="text" class="form-control " name="e" placeholder="Enter Email Address">
</div>
<div class="mb-5 ms-3" style="width:50%;">
    <button type="submit" class="form-control btn btn-warning fw-bold">Register</button>
</div>

  </form>
        </div>
  </center>

{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    {% if p %}
    <div class="row mt-3">
        {% for i in p %}
        <div class="col-sm-4">
          <div class="card" style="width:100%;">
              <img src="{{i.image.url}}" class="card-img-top" alt="..." height="300px">
              <div class="card-body">
                <h5 class="card-title text-center">{{i.name}}</h5>
                  <h4 class="text-center">{{i.price}}</h4>
               <center> <a href="{% url 'shop:details' i.name %}" class="btn btn-primary">Products</a></center>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h3>No Results Found</h3>
    {% endif %}
</div>

{% endblock %}